services:
  - type: web
    name: tiktok-zefoy-comments-hearts
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: TIKTOK_URL
        value: "https://vt.tiktok.com/ZS9DYddHW9abm-CnX9Q/"
      - key: COMMENT_KEYWORD
        value: "ok"
      - key: COMMENT_USERNAME
        value: "dtt_027"
      - key: PORT
        value: "10000"
